language: java
jdk:
  - oraclejdk8
install : mvn package

deploy:
  provider: heroku
  api_key:
    secure: YZkhsGsXgHEbLYZISm5zS3OpVyDkjTRCiAYF5qI9Qipd4QIylYq+sqEm9BGGRlfIT6bJoYdWUHAZCJoAiyb6qs/J+3E+xi7vlNEOAjeavBVZQUT/jERCLNw4CDatA/NYIdwi3a118xCIF7KG/IfPD8KiKdD91BqddtzpTZfqCkdlCzJGrGlAgS+RLeTK/OvTK+lflPltWq12bGkiT+M6W9UY16a+aLF1lhsJkcpMVdHTDJ4tVq2V4RoVlYmjsgJdPDFdsWVCUDCudv2/JopWS09jtc+D7lqRi7R+A4INugHk/bhGCF7RwD+piC+7qiH+QoxI/ZFbfq36lr26quTldDPnwXaDQQv6Gu3PiB1Zs8nisPl1qKgG8w43cAQTxsd0bE3I+sqzhnrWx+ei+V1KihTaMeP8TKylnaf++EMzs1TrODglFAGu4nK8TUuawYZk9gQBUCN14E95gxFVSo0tbwjwXirJ53Z3wtEUj5zKu3rF51MwwqRnn5zb2CvGzJZLTyYtOTU3CVT7JOwm0enWyRkVOxOQ2cl+aJZ4z+OGMx9+36/6l2E0DeDDXH3jjVqDA4V+h+AnRAcwj7bHzADJcukdBKdC5DWNmXoBJVuNb8NfJ4yjJZDevE2TvZDuxSKjy8i8uEgnQQ2LobdT253fsEfi8MYjC1VuCef5Uhi7U9o=
  app: secure-caverns-39897
  on:
    repo: nicolasMachut/ArcaRestfullApi
